# Generated by Django 4.0 on 2023-02-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('JOIN', 'JOIN'), ('PASSWORD_CHANGE', 'PASSWORD_CHANGE')], max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'sww_verification_emails',
                'ordering': ['-created_date'],
            },
        ),
    ]
